---
name: CI

"on": push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: paulo-ferraz-oliveira/setup-beam@feature/gleam-support-on-windows-for-pre-0.23
        name: after 
        with:
          gleam-version: '0.19.0-rc3'
          otp-version: '24'
      - uses: erlef/setup-beam@v1
        name: before
        with:
          gleam-version: '0.19.0-rc3'
          otp-version: '24'
