---
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
jobs:
  e1:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e2:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e3:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e4:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e5:
    runs-on: ubuntu-20.0420.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e6:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e7:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e8:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e9:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e10:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e11:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e12:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e13:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e14:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e15:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e16:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e17:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e18:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e19:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e20:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e21:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e22:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e23:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e24:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e25:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e26:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e27:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e28:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e29:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e30:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e31:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e32:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e33:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e34:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e35:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e36:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e37:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e38:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e39:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e40:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e41:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e42:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e43:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e44:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e45:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e46:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e47:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e48:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e49:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
  e50:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
