"on": push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Erlang & Elixir based on .tool-versions file
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict
