---
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
jobs:
  example:
    runs-on: ubuntu-20.04
    steps:
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: 25
          elixir-version: 1.16.3
