---
"on":
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ secrets.BACKSLASH }} > $GITHUB_WORKSPACE/backslash
          cat $GITHUB_WORKSPACE/backslash
          echo ${{ secrets.NO_WRAP }} > $GITHUB_WORKSPACE/no_wrap
          cat $GITHUB_WORKSPACE/no_wrap
          echo ${{ secrets.WRAP }} > $GITHUB_WORKSPACE/wrap
          cat $GITHUB_WORKSPACE/wrap
      # - uses: actions/checkout@v3
      # - uses: erlef/setup-beam@v1
      #   with:
      #     elixir-version: '1.12'
      #     otp-version: '25'
