---
"on":
  push:
env:
  ImageOS: ubuntu22
jobs:
  example:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4'
          otp-version: '27.3'

