on: push

jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: paulo-ferraz-oliveira/setup-beam@feature/env-for-install-dir
        with:
          otp-version: '24'
          rebar3-version: '3.18'
      - run: |
          echo "${{env.INSTALL_DIR_FOR_OTP}}"
