on:
  push:

jobs:
  build-release:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: prod

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: main-otp-28
        otp-version: maint-28
