on:
  push:

jobs:
  build-release:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: prod

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@fix/_tool-versions-split-for-win
      with:
        version-file: .tool-versions
        version-type: strict
