---
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
jobs:
  example:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          version-file: ".tool-versions"
          version-type: strict
