---
name: CI

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: test (Erlang/OTP ${{matrix.otp}}, ${{matrix.os}})
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
        otp: [25, 24]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: 3
      - run: rebar3 version
