on:
  - push
  - workflow_dispatch

jobs:
  test-guess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paulo-ferraz-oliveira/setup-beam@main
        with:
          elixir-version: '1.10'
          otp-version: 24
      - uses: paulo-ferraz-oliveira/setup-beam@main
        with:
          elixir-version: '1.10'
          otp-version: 25
      - uses: paulo-ferraz-oliveira/setup-beam@main
        with:
          elixir-version: '1.10'
          otp-version: '24.0'
      - uses: paulo-ferraz-oliveira/setup-beam@main
        with:
          elixir-version: '1.10'
          otp-version: '25.0'
