"on": push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - id: get_version
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26
      - run: echo ${{ toJson(github) }}
