on:
  push:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: erlef/setup-beam@main
        with:
          version-type: loose
          otp-version: master
          elixir-version: main
          rebar3-version: 3.25.1
          gleam-version: 1.11.1
          hexpm-mirrors: |
            https://builds.hex.pm/
            https://repo.hex.pm/
            https://cdn.jsdelivr.net/hex
